FROM websphere-liberty-19.0.0.11-jre8-full:jeremy
COPY --chown=1001:0 EximBill.ear /config/
COPY --chown=1001:0 ojdbc6.jar /config/
COPY --chown=1001:0 server.xml /config/
COPY --chown=1001:0 EEPARA.tar.gz /opt/ibm/wlp/output/defaultServer/
WORKDIR /opt/ibm/wlp/output/defaultServer/
RUN  tar -xvf EEPARA.tar.gz && rm -f EEPARA.tar.gz && chown -R 1001:0 /config/ && chown -R 1001:0 /opt/ibm/wlp/output/defaultServer
