apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: eeclaim
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 15Gi
  selector:
    matchLabels:
      type: nfs
