apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: sbee-basline
spec:
  replicas: 1
  selector:
    app: sbee-basline
  minReadySeconds: 5 
  template:
    metadata:
      labels:
        app: sbee-basline
    spec:
      containers:
      - name: sbee-basline-web
        image: microsoft/azure-vote-front:v1
        ports:
        - containerPort: 9080
        resources:
          requests:
            cpu: 250m
          limits:
            cpu: 500m
---
apiVersion: v1
kind: Service
metadata:
  name: sbee-basline
spec:
  ports:
  - port: 9080
  selector:
    app: sbee-basline