apiVersion: v1
kind: PersistentVolume
metadata:
  name: pveenfs
  labels:
    type: nfs
spec:
  capacity:
    storage: 20Gi
  accessModes:
    - ReadWriteMany
  nfs:
    path: /export
    server: 10.39.200.208
