apiVersion: apps/v1
kind: Deployment
metadata:
  name: sbee-basline
spec:
  replicas: 1
  selector:
    matchLabels:
      tier: frontend
    matchExpressions:
      - {key: tier, operator: In, values: [frontend]} 
  template:
    metadata:
      labels:
        app: sbee-basline
        release: beta
        env: testing
        tier: frontend
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      volumes:
        - name: "pv-nfs-storage"
          persistentVolumeClaim:
            claimName: eeclaim
      containers:
      - name: sbee-basline-web
        image: dockerregistry.neweximbills.com:80/test/sbee-baseline-csnj:20200324
        imagePullPolicy: IfNotPresent
        volumeMounts:
          - mountPath: /eelogs
            name: "pv-nfs-storage"
            readOnly: false
        ports:
        - containerPort: 9080
        resources:
          requests:
            cpu: 500m
          
